-- 1. 创建日记条目表 (diary_entries)
create table if not exists diary_entries (
  id bigint generated by default as identity primary key,
  date text not null,
  content text not null,
  image_url text,
  created_at timestamptz default now()
);

-- 2. 创建访客记录表 (visitor_logs)
create table if not exists visitor_logs (
  id bigint generated by default as identity primary key,
  ip_address text,
  country text,
  region text,
  city text,
  isp text,
  visit_time timestamptz default now()
);

-- 3. 启用行级安全 (RLS)
alter table diary_entries enable row level security;
alter table visitor_logs enable row level security;

-- 4. 创建允许所有匿名用户读写的策略 (方便开发，无需鉴权)

-- diary_entries 策略
drop policy if exists "Enable read access for all users" on diary_entries;
create policy "Enable read access for all users"
on diary_entries for select
to anon
using (true);

drop policy if exists "Enable insert access for all users" on diary_entries;
create policy "Enable insert access for all users"
on diary_entries for insert
to anon
with check (true);

-- visitor_logs 策略
drop policy if exists "Enable read access for all users" on visitor_logs;
create policy "Enable read access for all users"
on visitor_logs for select
to anon
using (true);

drop policy if exists "Enable insert access for all users" on visitor_logs;
create policy "Enable insert access for all users"
on visitor_logs for insert
to anon
with check (true);

-- 5. 创建存储桶 (Storage Bucket) 用于存放图片
-- 注意：存储桶需要在 Storage 页面手动创建，或者使用 SQL 创建 (Supabase SQL 支持有限，建议手动确认)
insert into storage.buckets (id, name, public)
values ('diary_images', 'diary_images', true)
on conflict (id) do nothing;

-- 6. 创建存储桶策略 (允许匿名上传和查看)
drop policy if exists "Give anon users access to images" on storage.objects;
create policy "Give anon users access to images"
on storage.objects for select
to anon
using ( bucket_id = 'diary_images' );

drop policy if exists "Give anon users upload access" on storage.objects;
create policy "Give anon users upload access"
on storage.objects for insert
to anon
with check ( bucket_id = 'diary_images' );
